name: "build nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Enable magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build
    - run: nix flake check
