name: rust build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

  check:
    name: cargo check
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: cargo check

  test:
    name: cargo test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: cargo test


  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - run: cargo clippy --tests -- -Dclippy::all
