name: update dependencies
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 4 * * *' # at 04:00 every day

jobs:
  cargo:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: nix shell nixpkgs#cargo --command cargo update

  flake:
    runs-on: self-hosted
    needs: cargo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: nix flake update
      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@main
      - run: nix build
      - name: Update Nix Flake Lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "flake: update flake.lock"
          pr-labels: |
            dependencies
            automated
